CREATE TABLE TRIPS
(
   id BIGINT NOT NULL AUTO_INCREMENT,
   name VARCHAR(255) NOT NULL,
   trip_from VARCHAR(255) NOT NULL,
   trip_to VARCHAR(255) NOT NULL,
   distance DOUBLE PRECISION NOT NULL,
   owner BIGINT NOT NULL,
   PRIMARY KEY (id)
);

CREATE TABLE USERS
(
   id BIGINT NOT NULL AUTO_INCREMENT,
   name VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   PRIMARY KEY (id)
);