CREATE TABLE TRIPS
(
   id BIGINT NOT NULL AUTO_INCREMENT,
   name VARCHAR(255) NOT NULL,
   trip_from VARCHAR(255) NOT NULL,
   trip_to VARCHAR(255) NOT NULL,
   distance DOUBLE PRECISION NOT NULL,
   owner BIGINT NOT NULL,
   PRIMARY KEY (id)
);

CREATE TABLE USERS (
    id BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME NVARCHAR2(128) PRIMARY KEY,
    PASSWORD NVARCHAR2(128) NOT NULL,
    ROLE NVARCHAR2(128),
    EMAIL NVARCHAR2(128),
    ENABLED BOOL NOT NULL
);


CREATE TABLE AUTHORITIES (
    USERNAME NVARCHAR2(128) NOT NULL,
    AUTHORITY NVARCHAR2(128) NOT NULL
);
